version: "3.1"

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: dev
    # ports:
    #   - 27017:27017

  be:
    image: $PROJECT_NAME/be
    build: be
    environment:
      MONGODB_URL: "mongodb+srv://root:example@db/dev?retryWrites=true&w=majority"
    volumes:
      - ./be:/src
    ports:
      - 5123:5000
    depends_on:
      - db

  # fe:
  #   image: $PROJECT_NAME/fe
  #   build: be
  #   environment:
  #     - COMPOSE_PROJECT_NAME
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - be
