[tool.poetry]
name = "inventarr-be"
version = "0.1.0"
description = "backend for Inventarr, an inventory management tool"
authors = ["Matthew Hellmer <theprankmonkey@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["standard"], version = "^0.115.5"}
uvicorn = {extras = ["standard"], version = "^0.32.1"}
sqlmodel = "^0.0.22"
pydantic = "^2.10.2"
alembic = "^1.14.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
black = "^24.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "app.start:run"
